name: Deploy at Vercel

on:
  push:
      branches:
        - '**'
        - '!main'

jobs:
  vercel:
    runs-on: ubuntu-latest
    name: "Deploy application"
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org/
      - uses: amondnet/vercel-action@225d234cfe5340ca1f9a6cd158338126b5b6845f
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./
          vercel-args: '--prod'